export const alpacaConfig = [
  {
    id: 0,
    label: "Backgrounds",
    dir: "backgrounds",
    selected: false,
    items: [
      { id: 0, label: "Default", fileName: "default", selected: false },
      { id: 1, label: "Blue50", fileName: "blue50", selected: false },
      { id: 2, label: "Blue60", fileName: "blue60", selected: false },
      { id: 3, label: "Blue70", fileName: "blue70", selected: false },
      { id: 4, label: "Darkblue30", fileName: "darkblue30", selected: false },
      { id: 5, label: "Darkblue50", fileName: "darkblue50", selected: false },
      { id: 6, label: "Darkblue70", fileName: "darkblue70", selected: false },
      { id: 7, label: "Green50", fileName: "green50", selected: false },
      { id: 8, label: "Green60", fileName: "green60", selected: false },
      { id: 9, label: "Green70", fileName: "green70", selected: false },
      { id: 10, label: "Grey40", fileName: "grey40", selected: false },
      { id: 11, label: "Grey70", fileName: "grey70", selected: false },
      { id: 12, label: "Grey80", fileName: "grey80", selected: false },
      { id: 13, label: "Red50", fileName: "red50", selected: false },
      { id: 14, label: "Red60", fileName: "red60", selected: false },
      { id: 15, label: "Red70", fileName: "red70", selected: false },
      { id: 16, label: "Yellow50", fileName: "yellow50", selected: false },
      { id: 17, label: "Yellow60", fileName: "yellow60", selected: false },
    ],
  },
  {
    id: 1,
    label: "Ears",
    dir: "ears",
    selected: false,
    items: [
      { id: 0, label: "Default", fileName: "default", selected: false },
      {
        id: 1,
        label: "Tilt-Backward",
        fileName: "tilt-backward",
        selected: false,
      },
      {
        id: 2,
        label: "TIlt-Forward",
        fileName: "tilt-forward",
        selected: false,
      },
    ],
  },
  {
    id: 2,
    label: "Eyes",
    dir: "eyes",
    selected: false,
    items: [
      { id: 0, label: "Default", fileName: "default", selected: false },
      { id: 1, label: "Angry", fileName: "angry", selected: false },
      { id: 2, label: "Naughty", fileName: "naughty", selected: false },
      { id: 3, label: "Panda", fileName: "panda", selected: false },
      { id: 4, label: "Smart", fileName: "smart", selected: false },
      { id: 5, label: "Star", fileName: "star", selected: false },
    ],
  },
  {
    id: 3,
    label: "Hair",
    dir: "hair",
    selected: false,
    items: [
      { id: 0, label: "Default", fileName: "default", selected: false },
      { id: 1, label: "Bang", fileName: "bang", selected: false },
      { id: 2, label: "Curls", fileName: "curls", selected: false },
      { id: 3, label: "Elegant", fileName: "elegant", selected: false },
      { id: 4, label: "Fancy", fileName: "fancy", selected: false },
      { id: 5, label: "Quiff", fileName: "quiff", selected: false },
      { id: 6, label: "Short", fileName: "short", selected: false },
    ],
  },
  {
    id: 4,
    label: "Leg",
    dir: "leg",
    selected: false,
    items: [
      { id: 0, label: "Default", fileName: "default", selected: false },
      { id: 1, label: "Bubble-Tea", fileName: "bubble-tea", selected: false },
      { id: 2, label: "Cookie", fileName: "cookie", selected: false },
      {
        id: 3,
        label: "Game-Console",
        fileName: "game-console",
        selected: false,
      },
      {
        id: 4,
        label: "Tilt-Backward",
        fileName: "tilt-backward",
        selected: false,
      },
      {
        id: 5,
        label: "Tilt-Forward",
        fileName: "tilt-forward",
        selected: false,
      },
    ],
  },
  {
    id: 5,
    label: "Mouth",
    dir: "mouth",
    selected: false,
    items: [
      { id: 0, label: "Default", fileName: "default", selected: false },
      { id: 1, label: "Astonished", fileName: "astonished", selected: false },
      { id: 2, label: "Eating", fileName: "eating", selected: false },
      { id: 3, label: "Laugh", fileName: "laugh", selected: false },
      { id: 4, label: "Tongue", fileName: "tongue", selected: false },
    ],
  },
  {
    id: 6,
    label: "Neck",
    dir: "neck",
    selected: false,
    items: [
      { id: 0, label: "Default", fileName: "default", selected: false },
      {
        id: 1,
        label: "Bend-Backward",
        fileName: "bend-backward",
        selected: false,
      },
      {
        id: 2,
        label: "Bend-Forward",
        fileName: "bend-forward",
        selected: false,
      },
      { id: 3, label: "Thick", fileName: "thick", selected: false },
    ],
  },
  {
    id: 7,
    label: "Accessories",
    dir: "accessories",
    selected: false,
    items: [
      { id: 0, label: "Default", fileName: "default", selected: false },
      { id: 1, label: "Earings", fileName: "earings", selected: false },
      { id: 2, label: "Flower", fileName: "flower", selected: false },
      { id: 3, label: "Glasses", fileName: "glasses", selected: false },
    ],
  },
  {
    id: 8,
    label: "Nose",
    dir: "nose",
    selected: false,
    items: [{ id: 0, label: "Default", fileName: "default", selected: false }],
  },
];
